# Generated by Django 3.1.6 on 2021-02-08 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210204_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='products_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
